# Generated by Django 4.0.6 on 2023-04-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unmismatch3d', '0003_message_delete_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
