# Generated by Django 4.0.6 on 2023-04-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unmismatch3d', '0004_remove_message_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='media',
        ),
    ]
